fix dtype issue in exclusive_scan_decoupled_lookback_64 (#171153)
Summary:

Fixing the issue in [oncall post](https://fb.workplace.com/groups/gpuinference/permalink/3393438174138160/)

```
RuntimeError: Failed to run autotuning code block: An exception occurred in a subprocess:  
...  
AssertionError('initial value for `test_target` is of type int64, but the then block redefines it as int32')  

``` 

[re log](https://www.internalfb.com/manifold/explorer/lowering_run_logs/tree/remote_execution_logs/2142988542/1/7636d4532ef8dfab6afaa33e3bcc349d679be34de63b3d694e20918d8db5e3df%3A148/stderr)
traceback - P2093988183


**Technical context:**
At runtime:
test_target = -1 is only used to make the loop condition while test_target >= 0 false
It doesn't matter if it's int32 or int64 because -1 >= 0 is false regardless of dtype
The loop exits and the value is never used again

At compile time:
Triton's compiler analyzes all branches and checks type consistency
It sees test_target is initialized as index - 1 (int64)
Then in if flag == 2, it's reassigned to -1 (int32)
The compiler raises: 'initial value for test_target is of type int64[], but the then block redefines it as int32[]'

Test Plan:
* local lowering has succeeded

* re-publish with the built custom lowering pkg - ien.lower:de4373b
* unittest - `buck2 test //caffe2/torch/_inductor/runtime/tests:test_triton_helpers @//mode/dev-nosan`

Differential Revision: D89705211